# Generated by Django 3.1.3 on 2020-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_pk',
            field=models.IntegerField(default=True),
        ),
    ]
