# Generated by Django 3.1.3 on 2020-11-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_todo_likeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='likedUser',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
