# Generated by Django 3.1.3 on 2020-11-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201130_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='likedUser',
            field=models.TextField(blank=True),
        ),
    ]
