# Generated by Django 3.1.3 on 2020-12-01 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_commenttoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentToto',
            new_name='CommentTodo',
        ),
    ]
