# Generated by Django 3.1.3 on 2020-12-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_recommenttodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenttodo',
            name='todo_pk',
            field=models.IntegerField(default=True),
        ),
    ]
