# Generated by Django 3.1.3 on 2020-12-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_recommenttodo_todo_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='comment',
            new_name='updateCount',
        ),
        migrations.AddField(
            model_name='commenttodo',
            name='updateCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommenttodo',
            name='updateCount',
            field=models.IntegerField(default=0),
        ),
    ]
