# Generated by Django 3.1.3 on 2020-11-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201127_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.IntegerField(default=True),
        ),
    ]
