# Generated by Django 3.1.3 on 2020-11-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(default=models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
        ),
    ]
